<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emmanuel Yeboah">

<title>Endangered Languages: Predicting the degree of endangerment with country-level statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="proof_of_fit_model_files/libs/clipboard/clipboard.min.js"></script>
<script src="proof_of_fit_model_files/libs/quarto-html/quarto.js"></script>
<script src="proof_of_fit_model_files/libs/quarto-html/popper.min.js"></script>
<script src="proof_of_fit_model_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="proof_of_fit_model_files/libs/quarto-html/anchor.min.js"></script>
<link href="proof_of_fit_model_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="proof_of_fit_model_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="proof_of_fit_model_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="proof_of_fit_model_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="proof_of_fit_model_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#load-relevant-packages" id="toc-load-relevant-packages" class="nav-link active" data-scroll-target="#load-relevant-packages">Load Relevant Packages</a></li>
  <li><a href="#read-and-clean-data" id="toc-read-and-clean-data" class="nav-link" data-scroll-target="#read-and-clean-data">Read and clean data</a></li>
  <li><a href="#create-final-data-set" id="toc-create-final-data-set" class="nav-link" data-scroll-target="#create-final-data-set">Create final data set</a></li>
  <li><a href="#build-models" id="toc-build-models" class="nav-link" data-scroll-target="#build-models">Build Models</a>
  <ul class="collapse">
  <li><a href="#model-a-predict-numeric-degree-of-endangerment" id="toc-model-a-predict-numeric-degree-of-endangerment" class="nav-link" data-scroll-target="#model-a-predict-numeric-degree-of-endangerment">Model A: Predict Numeric Degree of Endangerment</a></li>
  <li><a href="#model-b-predict-probability-of-degree-of-endangerment" id="toc-model-b-predict-probability-of-degree-of-endangerment" class="nav-link" data-scroll-target="#model-b-predict-probability-of-degree-of-endangerment">Model B: Predict Probability of Degree of Endangerment</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Endangered Languages: Predicting the degree of endangerment with country-level statistics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emmanuel Yeboah </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="load-relevant-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-relevant-packages">Load Relevant Packages</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># for data manipulation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm) <span class="co"># for stan_glm stan_polr models</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rstanarm' was built under R version 4.3.1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'brms' was built under R version 4.3.1</code></pre>
</div>
</div>
</section>
<section id="read-and-clean-data" class="level2">
<h2 class="anchored" data-anchor-id="read-and-clean-data">Read and clean data</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read the data from website into R</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>raw_data_languages <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/mrbalikci/endangered-languages/master/data.csv'</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># clean the column names: remove spacing and special characters</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert values of all character columns to lower case</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, tolower) <span class="sc">|&gt;</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># some rows have multiple countries: create new rows for such rows</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_rows</span>(countries, country_codes_alpha_3, <span class="at">sep =</span> <span class="st">','</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_rows</span>(iso639_3_codes, <span class="at">sep =</span> <span class="st">','</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(id, countries, country_codes_alpha_3,iso639_3_codes, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Clean up country names: Remove anything at and after '(' symbol in the Name column</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">countries =</span> <span class="fu">str_replace_all</span>(countries, <span class="st">"</span><span class="sc">\\</span><span class="st">s*</span><span class="sc">\\</span><span class="st">(.*"</span>, <span class="st">""</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove white-spaces from the values of all character columns</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, str_squish)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>raw_data_countries <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/mrbalikci/endangered-languages/master/Countries.csv'</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># clean the column names: remove spacing and special characters</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()  <span class="sc">|&gt;</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert values of all character columns to lower case</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, tolower) <span class="sc">|&gt;</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># remove white-spaces from the values of all character columns</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, str_squish)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to inspect dataset</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw_data_languages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,635
Columns: 15
$ id                          &lt;dbl&gt; 1022, 1023, 383, 383, 383, 383, 383, 383, …
$ name_in_english             &lt;chr&gt; "south italian", "sicilian", "low saxon", …
$ name_in_french              &lt;chr&gt; "italien du sud", "sicilien", "bas-saxon",…
$ name_in_spanish             &lt;chr&gt; "napolitano-calabrés", "siciliano", "bajo …
$ countries                   &lt;chr&gt; "italy", "italy", "germany", "germany", "g…
$ country_codes_alpha_3       &lt;chr&gt; "ita", "ita", "deu", "deu", "deu", "deu", …
$ iso639_3_codes              &lt;chr&gt; "nap", "scn", "act", "drt", "frs", "gos", …
$ degree_of_endangerment      &lt;chr&gt; "vulnerable", "vulnerable", "vulnerable", …
$ alternate_names             &lt;chr&gt; "neapolitan; neapolitan-calabrese; неаполи…
$ name_in_the_language        &lt;chr&gt; NA, NA, "neddersassisch", "neddersassisch"…
$ number_of_speakers          &lt;dbl&gt; 7500000, 5000000, 4800000, 4800000, 480000…
$ sources                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ latitude                    &lt;dbl&gt; 40.9798, 37.4399, 53.4029, 53.4029, 53.402…
$ longitude                   &lt;dbl&gt; 15.2490, 14.5019, 10.3601, 10.3601, 10.360…
$ description_of_the_location &lt;chr&gt; "campania, lucania (basilicata), abruzzi (…</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to inspect dataset</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(raw_data_countries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 170
Columns: 8
$ country          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…
$ name             &lt;chr&gt; "albania", "algeria", "andorra", "angola", "anguilla"…
$ gdppc            &lt;dbl&gt; 3965, 4206, 42500, 4102, 8800, 13432, 3499, 56328, 43…
$ literacy         &lt;dbl&gt; 0.987, 0.800, 1.000, 0.711, 0.950, 0.981, 0.998, 0.99…
$ infant_mortality &lt;dbl&gt; 14.0, 27.7, 3.6, 76.5, 3.4, 11.1, 13.1, 3.2, 3.4, 24.…
$ agriculture      &lt;dbl&gt; 0.227, 0.107, 0.006, 0.050, 0.029, 0.082, 0.217, 0.02…
$ population       &lt;dbl&gt; 3038594, 39670000, 86165, 25020000, 15000, 43420000, …
$ net_migration    &lt;dbl&gt; -3.3, -0.9, 0.0, -0.1, 11.9, -0.1, -5.7, 5.6, 5.2, 0.…</code></pre>
</div>
</div>
</section>
<section id="create-final-data-set" class="level2">
<h2 class="anchored" data-anchor-id="create-final-data-set">Create final data set</h2>
<p>Join the languages data and the country-level statistics data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine languages data to countries data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> raw_data_languages <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    raw_data_countries,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"countries"</span> <span class="ot">=</span> <span class="st">"name"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,635
Columns: 22
$ id                          &lt;dbl&gt; 1022, 1023, 383, 383, 383, 383, 383, 383, …
$ name_in_english             &lt;chr&gt; "south italian", "sicilian", "low saxon", …
$ name_in_french              &lt;chr&gt; "italien du sud", "sicilien", "bas-saxon",…
$ name_in_spanish             &lt;chr&gt; "napolitano-calabrés", "siciliano", "bajo …
$ countries                   &lt;chr&gt; "italy", "italy", "germany", "germany", "g…
$ country_codes_alpha_3       &lt;chr&gt; "ita", "ita", "deu", "deu", "deu", "deu", …
$ iso639_3_codes              &lt;chr&gt; "nap", "scn", "act", "drt", "frs", "gos", …
$ degree_of_endangerment      &lt;chr&gt; "vulnerable", "vulnerable", "vulnerable", …
$ alternate_names             &lt;chr&gt; "neapolitan; neapolitan-calabrese; неаполи…
$ name_in_the_language        &lt;chr&gt; NA, NA, "neddersassisch", "neddersassisch"…
$ number_of_speakers          &lt;dbl&gt; 7500000, 5000000, 4800000, 4800000, 480000…
$ sources                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ latitude                    &lt;dbl&gt; 40.9798, 37.4399, 53.4029, 53.4029, 53.402…
$ longitude                   &lt;dbl&gt; 15.2490, 14.5019, 10.3601, 10.3601, 10.360…
$ description_of_the_location &lt;chr&gt; "campania, lucania (basilicata), abruzzi (…
$ country                     &lt;dbl&gt; 76, 76, 60, 60, 60, 60, 60, 60, 60, 60, 60…
$ gdppc                       &lt;dbl&gt; 29847, 29847, 41219, 41219, 41219, 41219, …
$ literacy                    &lt;dbl&gt; 0.992, 0.992, 0.990, 0.990, 0.990, 0.990, …
$ infant_mortality            &lt;dbl&gt; 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.…
$ agriculture                 &lt;dbl&gt; 0.022, 0.022, 0.007, 0.007, 0.007, 0.007, …
$ population                  &lt;dbl&gt; 60800000, 60800000, 81410000, 81410000, 81…
$ net_migration               &lt;dbl&gt; 3.9, 3.9, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.…</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>the_levels_of_endangerment <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"vulnerable"</span>, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"definitely endangered"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"severely endangered"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"critically endangered"</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"extinct"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Creating a numeric version of degree of endangerment</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">degree_of_endangerment_numeric =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>      degree_of_endangerment <span class="sc">==</span> <span class="st">"vulnerable"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>      degree_of_endangerment <span class="sc">==</span> <span class="st">"definitely endangered"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>      degree_of_endangerment <span class="sc">==</span> <span class="st">"severely endangered"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>      degree_of_endangerment <span class="sc">==</span> <span class="st">"critically endangered"</span> <span class="sc">~</span> <span class="dv">4</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>      degree_of_endangerment <span class="sc">==</span> <span class="st">"extinct"</span> <span class="sc">~</span> <span class="dv">5</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#creating an ordred factor version of degree of endangerment </span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">degree_of_endangerment_factor =</span> <span class="fu">factor</span>(degree_of_endangerment,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">levels =</span> the_levels_of_endangerment,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,635
Columns: 24
$ id                             &lt;dbl&gt; 1022, 1023, 383, 383, 383, 383, 383, 38…
$ name_in_english                &lt;chr&gt; "south italian", "sicilian", "low saxon…
$ name_in_french                 &lt;chr&gt; "italien du sud", "sicilien", "bas-saxo…
$ name_in_spanish                &lt;chr&gt; "napolitano-calabrés", "siciliano", "ba…
$ countries                      &lt;chr&gt; "italy", "italy", "germany", "germany",…
$ country_codes_alpha_3          &lt;chr&gt; "ita", "ita", "deu", "deu", "deu", "deu…
$ iso639_3_codes                 &lt;chr&gt; "nap", "scn", "act", "drt", "frs", "gos…
$ degree_of_endangerment         &lt;chr&gt; "vulnerable", "vulnerable", "vulnerable…
$ alternate_names                &lt;chr&gt; "neapolitan; neapolitan-calabrese; неап…
$ name_in_the_language           &lt;chr&gt; NA, NA, "neddersassisch", "neddersassis…
$ number_of_speakers             &lt;dbl&gt; 7500000, 5000000, 4800000, 4800000, 480…
$ sources                        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ latitude                       &lt;dbl&gt; 40.9798, 37.4399, 53.4029, 53.4029, 53.…
$ longitude                      &lt;dbl&gt; 15.2490, 14.5019, 10.3601, 10.3601, 10.…
$ description_of_the_location    &lt;chr&gt; "campania, lucania (basilicata), abruzz…
$ country                        &lt;dbl&gt; 76, 76, 60, 60, 60, 60, 60, 60, 60, 60,…
$ gdppc                          &lt;dbl&gt; 29847, 29847, 41219, 41219, 41219, 4121…
$ literacy                       &lt;dbl&gt; 0.992, 0.992, 0.990, 0.990, 0.990, 0.99…
$ infant_mortality               &lt;dbl&gt; 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4,…
$ agriculture                    &lt;dbl&gt; 0.022, 0.022, 0.007, 0.007, 0.007, 0.00…
$ population                     &lt;dbl&gt; 60800000, 60800000, 81410000, 81410000,…
$ net_migration                  &lt;dbl&gt; 3.9, 3.9, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,…
$ degree_of_endangerment_numeric &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ degree_of_endangerment_factor  &lt;ord&gt; vulnerable, vulnerable, vulnerable, vul…</code></pre>
</div>
</div>
</section>
<section id="build-models" class="level2">
<h2 class="anchored" data-anchor-id="build-models">Build Models</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>covariates <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 'gdppc',</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">'literacy'</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">'infant_mortality'</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">'agriculture'</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 'population',</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">'net_migration'</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ,</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 'latitude',</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 'longitude',</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 'number_of_speakers'</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="model-a-predict-numeric-degree-of-endangerment" class="level3">
<h3 class="anchored" data-anchor-id="model-a-predict-numeric-degree-of-endangerment">Model A: Predict Numeric Degree of Endangerment</h3>
<p><span class="math display">\[
\begin{aligned}
\operatorname{degree\_of\_endangerment\_numeric} &amp;= \alpha + \beta_{1}(\operatorname{literacy}) + \beta_{2}(\operatorname{infant\_mortality}) + \beta_{3}(\operatorname{agriculture})\ + \\
&amp;\quad \beta_{4}(\operatorname{net\_migration}) + \epsilon
\end{aligned}
\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model_formula_numeric <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'degree_of_endangerment_numeric ~ '</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(covariates, <span class="at">collapse =</span> <span class="st">'+'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>model_formula_numeric</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>degree_of_endangerment_numeric ~ literacy + infant_mortality + 
    agriculture + net_migration</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting the degree of endangerment as a number</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model_numeric <span class="ot">&lt;-</span> <span class="fu">stan_glm</span>(<span class="at">data =</span> combined_data, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> model_formula_numeric, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> gaussian, </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">seed =</span> <span class="dv">9</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>model_numeric</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      degree_of_endangerment_numeric ~ literacy + infant_mortality + 
       agriculture + net_migration
 observations: 3007
 predictors:   5
------
                 Median MAD_SD
(Intercept)      1.9    0.1   
literacy         0.3    0.1   
infant_mortality 0.0    0.0   
agriculture      0.7    0.4   
net_migration    0.0    0.0   

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.2    0.0   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>broom.mixed<span class="sc">::</span><span class="fu">tidy</span>(model_numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  term             estimate std.error
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)       1.93      0.149  
2 literacy          0.278     0.142  
3 infant_mortality  0.00844   0.00203
4 agriculture       0.683     0.365  
5 net_migration     0.0436    0.0104 </code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
\operatorname{\widehat{degree\_of\_endangerment\_numeric}} &amp;= 1.931 + 0.278(\operatorname{literacy}) + 0.008(\operatorname{infant\_mortality})\ + \\
&amp;\quad 0.683(\operatorname{agriculture}) + 0.044(\operatorname{net\_migration})
\end{aligned}
\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_numeric, <span class="st">"areas"</span>, <span class="at">regex_pars =</span> <span class="fu">c</span>(<span class="st">'literacy'</span>, <span class="st">'agriculture'</span>),</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">prob_outer =</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="proof_of_fit_model_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_numeric, <span class="st">"areas"</span>, <span class="at">regex_pars =</span> <span class="fu">c</span>(<span class="st">'infant_mortality'</span>,<span class="st">'net_migration'</span>),</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">prob_outer =</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="proof_of_fit_model_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="model-b-predict-probability-of-degree-of-endangerment" class="level3">
<h3 class="anchored" data-anchor-id="model-b-predict-probability-of-degree-of-endangerment">Model B: Predict Probability of Degree of Endangerment</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model_formula_factor <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'degree_of_endangerment_factor ~ '</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(covariates, <span class="at">collapse =</span> <span class="st">'+'</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>model_formula_factor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>degree_of_endangerment_factor ~ literacy + infant_mortality + 
    agriculture + net_migration</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
\log\left[ \frac { P( \operatorname{vulnerable} \geq \operatorname{definitely\ endangered} ) }{ 1 - P( \operatorname{vulnerable} \geq \operatorname{definitely\ endangered} ) } \right] &amp;= \alpha_{1} + \beta_{1}(\operatorname{literacy}) + \beta_{2}(\operatorname{infant\_mortality}) + \beta_{3}(\operatorname{agriculture})\ + \\
&amp;\quad \beta_{4}(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{definitely\ endangered} \geq \operatorname{severely\ endangered} ) }{ 1 - P( \operatorname{definitely\ endangered} \geq \operatorname{severely\ endangered} ) } \right] &amp;= \alpha_{2} + \beta_{1}(\operatorname{literacy}) + \beta_{2}(\operatorname{infant\_mortality}) + \beta_{3}(\operatorname{agriculture})\ + \\
&amp;\quad \beta_{4}(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{severely\ endangered} \geq \operatorname{critically\ endangered} ) }{ 1 - P( \operatorname{severely\ endangered} \geq \operatorname{critically\ endangered} ) } \right] &amp;= \alpha_{3} + \beta_{1}(\operatorname{literacy}) + \beta_{2}(\operatorname{infant\_mortality}) + \beta_{3}(\operatorname{agriculture})\ + \\
&amp;\quad \beta_{4}(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{critically\ endangered} \geq \operatorname{extinct} ) }{ 1 - P( \operatorname{critically\ endangered} \geq \operatorname{extinct} ) } \right] &amp;= \alpha_{4} + \beta_{1}(\operatorname{literacy}) + \beta_{2}(\operatorname{infant\_mortality}) + \beta_{3}(\operatorname{agriculture})\ + \\
&amp;\quad \beta_{4}(\operatorname{net\_migration})
\end{aligned}
\]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicting the PROBABILITY of endangerment of each of the degrees of endangerment</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model_factor <span class="ot">&lt;-</span> <span class="fu">stan_polr</span>(<span class="at">data =</span> combined_data, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> model_formula_factor, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"logistic"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">prior =</span> <span class="fu">R2</span>(<span class="fl">0.25</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">seed =</span> <span class="dv">9</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>model_factor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>stan_polr
 family:       ordered [logistic]
 formula:      degree_of_endangerment_factor ~ literacy + infant_mortality + 
       agriculture + net_migration
 observations: 3007
------
                 Median MAD_SD
literacy         0.4    0.2   
infant_mortality 0.0    0.0   
agriculture      1.1    0.5   
net_migration    0.1    0.0   

Cutpoints:
                                          Median MAD_SD
vulnerable|definitely endangered          -0.3    0.2  
definitely endangered|severely endangered  1.1    0.2  
severely endangered|critically endangered  1.9    0.2  
critically endangered|extinct              3.4    0.2  

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>broom.mixed<span class="sc">::</span><span class="fu">tidy</span>(model_factor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  term                                      estimate std.error
  &lt;chr&gt;                                        &lt;dbl&gt;     &lt;dbl&gt;
1 literacy                                    0.376    0.203  
2 infant_mortality                            0.0110   0.00302
3 agriculture                                 1.06     0.515  
4 net_migration                               0.0637   0.0151 
5 vulnerable|definitely endangered           -0.338    0.221  
6 definitely endangered|severely endangered   1.06     0.219  
7 severely endangered|critically endangered   1.91     0.219  
8 critically endangered|extinct               3.41     0.239  </code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
\log\left[ \frac { P( \operatorname{vulnerable} \geq \operatorname{definitely\ endangered} ) }{ 1 - P( \operatorname{vulnerable} \geq \operatorname{definitely\ endangered} ) } \right] &amp;= -0.338 + 0.376(\operatorname{literacy}) + 0.011(\operatorname{infant\_mortality})\ + \\
&amp;\quad 1.063(\operatorname{agriculture}) + 0.064(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{definitely\ endangered} \geq \operatorname{severely\ endangered} ) }{ 1 - P( \operatorname{definitely\ endangered} \geq \operatorname{severely\ endangered} ) } \right] &amp;= 1.059 + 0.376(\operatorname{literacy}) + 0.011(\operatorname{infant\_mortality})\ + \\
&amp;\quad 1.063(\operatorname{agriculture}) + 0.064(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{severely\ endangered} \geq \operatorname{critically\ endangered} ) }{ 1 - P( \operatorname{severely\ endangered} \geq \operatorname{critically\ endangered} ) } \right] &amp;= 1.908 + 0.376(\operatorname{literacy}) + 0.011(\operatorname{infant\_mortality})\ + \\
&amp;\quad 1.063(\operatorname{agriculture}) + 0.064(\operatorname{net\_migration}) \\
\log\left[ \frac { P( \operatorname{critically\ endangered} \geq \operatorname{extinct} ) }{ 1 - P( \operatorname{critically\ endangered} \geq \operatorname{extinct} ) } \right] &amp;= 3.4412 + 0.376(\operatorname{literacy}) + 0.011(\operatorname{infant\_mortality})\ + \\
&amp;\quad 1.063(\operatorname{agriculture}) + 0.064(\operatorname{net\_migration})
\end{aligned}
\]</span></p>
<div class="cell">

</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_factor, <span class="st">"areas"</span>, <span class="at">regex_pars =</span> <span class="fu">c</span>(<span class="st">'literacy'</span>, <span class="st">'agriculture'</span>),</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">prob_outer =</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="proof_of_fit_model_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_factor, <span class="st">"areas"</span>, <span class="at">regex_pars =</span> <span class="fu">c</span>(<span class="st">'infant_mortality'</span>,<span class="st">'net_migration'</span>),</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">prob_outer =</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="proof_of_fit_model_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>